import "./globals.scss";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" flex flex-col min-h-screen">
        <Navbar />
        <div className="flex-grow ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
